version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: 'Billinho-db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data' 
    networks:
      - compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin-container'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'lucas.olopes@redealumni.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - compose-network
  rails:
    build: .
    container_name: 'rails-container'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Billinho
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - compose-network
networks: 
  compose-network:
    driver: bridge
  